name: nstack_sdk
description: Nstack SDK for Flutter.
version: 0.1.5
author: Nodes Agency
homepage: https://github.com/nstack-io/flutter-sdk

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  nstack_api:
    path: ../nstack_api
  package_info: ^2.0.2
  device_info: ^2.0.2
  cross_local_storage: ^2.0.1
  get_it: ^7.2.0
  uuid: ^3.0.4
  dart_style: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dk.nodes.nstack
        pluginClass: NstackPlugin
      ios:
        pluginClass: NstackPlugin

