name: nstack_sdk
description: Nstack SDK for Flutter.
version: 0.1.5
author: Nodes Agency
homepage: https://github.com/nstack-io/flutter-sdk

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  nstack_api:
    path: ../api
  meta: ^1.1.8
  http: ^0.12.1
  build: 1.3.0
  build_config: ^0.4.2
  get_version: ^0.2.2
  device_info: 0.4.2+4
  cross_local_storage: ^1.1.1
  get_it: ^4.0.4
  uuid: 2.0.4
  dart_style: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dk.nodes.nstack
        pluginClass: NstackPlugin
      ios:
        pluginClass: NstackPlugin

