name: nstacktooling
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.4
  yaml: ^2.2.0
  args: ^1.6.0
  dart_style: ^1.3.3
  logging: ^0.11.4
  watcher: ^0.9.7+14
  http: ^0.12.0+4
  html: ^0.14.0+3

dev_dependencies:
  build_runner: ^1.8.0
  build_version: ^2.0.1
  pedantic: ^1.9.0
  test: ^1.14.2

executables:
  nstacktooling: main